# Generated by Django 5.2.7 on 2026-09-14 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0004_alter_tokenproxy_options'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiToken',
            fields=[
            ],
            options={
                'verbose_name': 'API token',
                'verbose_name_plural': 'API tokens',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('authtoken.tokenproxy',),
        ),
    ]
