# Generated by Django 5.2.7 on 2026-09-15 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_apitoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='health_summary',
            field=models.TextField(blank=True),
        ),
    ]
