# Generated by Django 5.2.7 on 2025-10-12 16:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('LAB', 'Laboratory Report'), ('BLOOD', 'Blood Test'), ('URINE', 'Urine Test'), ('XRAY', 'X-Ray'), ('MRI', 'MRI Scan'), ('CT', 'CT Scan'), ('OTHER', 'Other')], default='LAB', max_length=10)),
                ('lab_name', models.CharField(blank=True, max_length=200)),
                ('report_date', models.DateField()),
                ('file', models.FileField(upload_to='medical_reports/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('parsed_data', models.JSONField(blank=True, default=dict)),
                ('is_parsed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-report_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=100)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('reference_range', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(blank=True, choices=[('NORMAL', 'Normal'), ('HIGH', 'High'), ('LOW', 'Low'), ('ABNORMAL', 'Abnormal')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['test_name'],
            },
        ),
    ]
