# Generated by Django 5.2.7 on 2025-10-15 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_reports', '0003_allow_null_unit_reference_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='unit',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
