# Generated by Django 5.2.7 on 2026-09-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_reports', '0007_restrict_report_uploads_to_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalreport',
            name='ai_review',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
