# Generated by Django 5.2.7 on 2026-09-16 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_reports', '0008_medicalreport_ai_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalreport',
            name='ai_chat',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
