# Generated by Django 5.2.7 on 2025-10-15 04:59

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabTestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('display_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('default_unit', models.CharField(max_length=50)),
                ('normal_min', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('normal_max', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lab Test Type',
                'verbose_name_plural': 'Lab Test Types',
                'ordering': ['category', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='LabTestUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('symbol', models.CharField(blank=True, max_length=20)),
                ('category', models.CharField(max_length=50)),
                ('is_base_unit', models.BooleanField(default=False)),
                ('conversion_factor', models.DecimalField(decimal_places=8, default=Decimal('1.0'), help_text='Factor to convert to base unit', max_digits=15)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lab Test Unit',
                'verbose_name_plural': 'Lab Test Units',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LabTestPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_name', models.CharField(max_length=100)),
                ('regex_pattern', models.TextField(help_text='Regex pattern for matching this test in PDF text')),
                ('priority', models.IntegerField(default=1, help_text='Higher priority patterns are tried first')),
                ('value_group', models.IntegerField(default=1, help_text='Regex group number containing the value')),
                ('unit_group', models.IntegerField(blank=True, help_text='Regex group number containing the unit', null=True)),
                ('range_group', models.IntegerField(blank=True, help_text='Regex group number containing the reference range', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('test_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patterns', to='lab_tests.labtesttype')),
            ],
            options={
                'verbose_name': 'Lab Test Pattern',
                'verbose_name_plural': 'Lab Test Patterns',
                'ordering': ['test_type', '-priority', 'pattern_name'],
            },
        ),
        migrations.CreateModel(
            name='LabTestTypeUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normal_min', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('normal_max', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('conversion_factor', models.DecimalField(decimal_places=8, default=Decimal('1.0'), max_digits=15)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('test_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supported_units', to='lab_tests.labtesttype')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_types', to='lab_tests.labtestunit')),
            ],
            options={
                'verbose_name': 'Test Type Unit',
                'verbose_name_plural': 'Test Type Units',
                'unique_together': {('test_type', 'unit')},
            },
        ),
        migrations.CreateModel(
            name='LabTestValidationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_value', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('normal_min', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('normal_max', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('critical_low_min', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('critical_high_max', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('test_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_rules', to='lab_tests.labtesttype')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_rules', to='lab_tests.labtestunit')),
            ],
            options={
                'verbose_name': 'Lab Test Validation Rule',
                'verbose_name_plural': 'Lab Test Validation Rules',
                'unique_together': {('test_type', 'unit')},
            },
        ),
        migrations.CreateModel(
            name='UnitConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversion_factor', models.DecimalField(decimal_places=8, help_text='Factor to convert from_unit to to_unit', max_digits=15)),
                ('reverse_factor', models.DecimalField(decimal_places=8, help_text='Factor to convert to_unit back to from_unit', max_digits=15)),
                ('formula', models.CharField(blank=True, help_text='Human-readable conversion formula', max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions_from', to='lab_tests.labtestunit')),
                ('to_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions_to', to='lab_tests.labtestunit')),
            ],
            options={
                'verbose_name': 'Unit Conversion',
                'verbose_name_plural': 'Unit Conversions',
                'unique_together': {('from_unit', 'to_unit')},
            },
        ),
    ]
