# Generated by Django 5.2.7 on 2026-09-15 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_tests', '0002_scope_unit_conversions_to_test_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTestAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The printed name as the user linked it', max_length=200)),
                ('match_key', models.CharField(help_text='lab_tests.matching.alias_key of the name', max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('test_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_aliases', to='lab_tests.labtesttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_aliases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Test Alias',
                'verbose_name_plural': 'User Test Aliases',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('user', 'match_key'), name='unique_user_test_alias')],
            },
        ),
    ]
