# Generated by Django 5.2.7 on 2026-09-16 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_tests', '0003_user_test_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtesttype',
            name='edited_by_user',
            field=models.BooleanField(default=False, help_text='Someone changed this entry in the app, so populate_lab_tests leaves it alone'),
        ),
        migrations.AddField(
            model_name='labtesttype',
            name='source',
            field=models.CharField(choices=[('catalog', 'Built in'), ('user', 'Added in the app')], default='catalog', max_length=10),
        ),
    ]
