# Generated by Django 5.2.7 on 2026-09-16 06:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0003_restrict_prescription_uploads_to_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='ai_chat',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='prescription',
            name='parse_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='file',
            field=models.FileField(upload_to='prescriptions/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp', 'bmp', 'tif', 'tiff', 'heic', 'heif'])]),
        ),
    ]
