# Generated by Django 5.2.7 on 2026-09-16 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0005_existing_prescriptions_are_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='ai_review',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
