"""
Django settings for diagnoseit_backend project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _env_bool(name: str, default: str = 'False') -> bool:
    return os.getenv(name, default).strip().lower() in ('1', 'true', 'yes', 'on')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# DEBUG: default False for safety. Override via env var for local dev.
DEBUG = _env_bool('DEBUG', 'False')

# SECRET_KEY: use the environment, or the key the Docker entrypoint saved in its data volume.
# `docker compose exec` starts a new process without the entrypoint's exported environment.
SECRET_KEY = os.getenv('SECRET_KEY', '').strip()
if not SECRET_KEY:
    key_file = BASE_DIR / 'data' / 'secret_key'
    if key_file.is_file():
        SECRET_KEY = key_file.read_text(encoding='utf-8').strip()
if not SECRET_KEY:
    raise ImproperlyConfigured(
        'SECRET_KEY must be set in the environment or saved in the app data volume.'
    )

# ALLOWED_HOSTS configuration
ALLOWED_HOSTS_ENV = os.getenv('ALLOWED_HOSTS', '127.0.0.1,localhost,backend')
ALLOWED_HOSTS = [host.strip() for host in ALLOWED_HOSTS_ENV.split(',')]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'users',
    'medical_reports',
    'prescriptions',
    'symptoms',
    'diagnosis',
    'lab_tests',
    'ai_settings',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'diagnoseit_backend.middleware.RequestLoggingMiddleware',  # Add request logging middleware
]

ROOT_URLCONF = 'diagnoseit_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'diagnoseit_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

if os.getenv('DATABASE_URL'):
    # Production database (PostgreSQL)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('POSTGRES_DB', 'diagnoseit'),
            'USER': os.getenv('POSTGRES_USER', 'diagnoseit'),
            'PASSWORD': os.getenv('POSTGRES_PASSWORD', 'diagnoseit_password'),
            'HOST': os.getenv('POSTGRES_HOST', 'db'),
            'PORT': os.getenv('POSTGRES_PORT', '5432'),
        }
    }
else:
    # Development database (SQLite)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'users.User'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# CORS: allow-all only in DEBUG; in production set CORS_ALLOWED_ORIGINS (comma-separated).
CORS_ALLOW_CREDENTIALS = True
if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True
    CORS_ALLOWED_ORIGINS: list[str] = []
else:
    CORS_ALLOW_ALL_ORIGINS = False
    CORS_ALLOWED_ORIGINS = [
        o.strip()
        for o in os.getenv('CORS_ALLOWED_ORIGINS', '').split(',')
        if o.strip()
    ]

# CSRF settings
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:3000',
    'http://127.0.0.1:3000',
    'http://localhost:8000',
    'http://127.0.0.1:8000',
]
_extra_csrf = os.getenv('CSRF_TRUSTED_ORIGINS', '')
if _extra_csrf.strip():
    CSRF_TRUSTED_ORIGINS.extend(
        x.strip() for x in _extra_csrf.split(',') if x.strip()
    )

CSRF_COOKIE_HTTPONLY = False
CSRF_USE_SESSIONS = False
CSRF_COOKIE_NAME = 'csrftoken'

CSRF_COOKIE_SAMESITE = 'Lax'
if DEBUG:
    CSRF_COOKIE_SECURE = False
    SESSION_COOKIE_SECURE = False
    SECURE_SSL_REDIRECT = False
else:
    # Production is HTTPS-only. Terminate TLS at the host reverse proxy and pass
    # X-Forwarded-Proto through the frontend proxy.
    CSRF_COOKIE_SECURE = _env_bool('CSRF_COOKIE_SECURE', 'True')
    SESSION_COOKIE_SECURE = _env_bool('SESSION_COOKIE_SECURE', 'True')
    SECURE_SSL_REDIRECT = _env_bool('SECURE_SSL_REDIRECT', 'True')
    SECURE_HSTS_SECONDS = int(os.getenv('SECURE_HSTS_SECONDS', '31536000'))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = _env_bool('SECURE_HSTS_INCLUDE_SUBDOMAINS', 'True')
    SECURE_HSTS_PRELOAD = _env_bool('SECURE_HSTS_PRELOAD', 'False')
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Anyone who can reach the server may create the first account, which becomes its administrator. Later
# accounts are added by an administrator in /admin, unless REGISTRATION_OPEN lets anyone sign up.
REGISTRATION_OPEN = _env_bool('REGISTRATION_OPEN', 'False')

# Login and sign-up limits count per client. Behind the bundled nginx every request comes from its
# address, so the client is read from the X-Real-IP header it sets.
RATELIMIT_IP_META_KEY = 'diagnoseit_backend.client_ip.client_ip'

# DRF's built-in tokens otherwise never expire. Set to 0 only for an explicitly
# accepted development exception.
API_TOKEN_TTL_DAYS = int(os.getenv('API_TOKEN_TTL_DAYS', '30'))

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'diagnoseit_backend.authentication.ExpiringTokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.MultiPartParser',
        'rest_framework.parsers.FormParser',
    ],
}

# File upload settings
FILE_UPLOAD_MAX_MEMORY_SIZE = 100 * 1024 * 1024  # 100MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 100 * 1024 * 1024  # 100MB

# Celery configuration
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", "redis://redis:6379/0")
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", "redis://redis:6379/0")
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 1800  # 30 minutes hard limit for VLM parsing
CELERY_TASK_SOFT_TIME_LIMIT = 1500  # 25 minutes soft limit
# AI reviews have their own queue, consumed by a worker with concurrency 1 (celery_review_worker in the compose
# files), so reviews reach the model server one at a time instead of competing for it and timing out.
CELERY_TASK_ROUTES = {
    "medical_reports.tasks.review_report_task": {"queue": "ai_review"},
}

# Logging configuration - Use Django's default
# LOGGING = {}  # Use Django's default logging
