# Generated by Django 5.2.7 on 2026-09-15 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='context',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
