# Generated by Django 5.2.7 on 2026-09-16 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0003_health_timeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='analysis',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
