# Generated by Django 5.2.7 on 2026-09-14 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIServiceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('diagnosis', 'AI diagnosis'), ('ocr', 'Report OCR'), ('report_review', 'Report review assistant')], max_length=32, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('provider', models.CharField(choices=[('openai', 'OpenAI-compatible API'), ('ollama', 'Ollama native API')], default='openai', max_length=16)),
                ('base_url', models.CharField(blank=True, help_text='For example http://localhost:8080/v1', max_length=500)),
                ('api_key', models.CharField(blank=True, max_length=500)),
                ('model', models.CharField(blank=True, max_length=200)),
                ('timeout_seconds', models.PositiveIntegerField(default=180)),
                ('max_tokens', models.PositiveIntegerField(default=1500)),
                ('ocr_mode', models.CharField(choices=[('auto', 'Auto-detect from model name'), ('paddle_ocr', 'PaddleOCR-VL (table and OCR prompts)'), ('json_vlm', 'Vision model returning JSON')], default='auto', max_length=16)),
                ('review_input', models.CharField(choices=[('auto', 'PDF text, or page images for scans'), ('text', 'PDF text only'), ('images', 'Page images (vision model)')], default='auto', max_length=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI service configuration',
            },
        ),
    ]
