# Generated by Django 5.2.7 on 2026-09-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiserviceconfig',
            name='auto_review',
            field=models.BooleanField(default=False, help_text='Report review only: review every report after it is parsed. Each report costs one or more model calls.'),
        ),
    ]
