# Generated by Django 5.2.7 on 2026-09-14 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_settings', '0002_aiserviceconfig_auto_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiserviceconfig',
            name='auto_apply',
            field=models.BooleanField(default=False, help_text='Report review only: apply safe fixes (removing rows that are not results, correcting units, reference ranges and status) for rows the model was shown. Adds, renames and value changes always wait for the user.'),
        ),
    ]
