# Generated by Django 5.2.7 on 2026-09-15 12:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_settings', '0003_aiserviceconfig_auto_apply'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiserviceconfig',
            name='temperature',
            field=models.FloatField(blank=True, help_text='Sampling temperature; blank uses the default for this service.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)]),
        ),
    ]
