# Generated by Django 5.2.7 on 2026-09-15 18:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_settings', '0004_aiserviceconfig_temperature'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiserviceconfig',
            name='parallel_requests',
            field=models.PositiveSmallIntegerField(default=1, help_text="Report OCR only: pages sent to the server at once; match the server's parallel slots.", validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(16)]),
        ),
    ]
